### ISSUE TITLE
NPM Audit Failure

### ISSUE THREAD

**Issue by Adam-Kernig** [micromatch/expand-braces#3]
The version of braces needs to be updated to 2.3.1 or higher

Package that is effected by this package:
https://github.com/karma-runner/karma

Advisory:
https://www.npmjs.com/advisories/786

**Comment by mobilutz** [comment]
See #2

**Comment by Adam-Kernig** [comment]
Thanks for that @mobilutz

**Comment by jonschlinkert** [comment]
duplicate
